AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS-SSO-Util-2020-11-08
Metadata:
  SSO:
    NumChildStacks: 10
Parameters:
  AccountParameter:
    Type: String
Resources:
  SomePSResource:
    Type: AWS::SSO::PermissionSet
    Properties:
      # InstanceArn: arn:aws:sso:::instance/ssoins-69e2ecd0b249f0cd
      Name: Foo
      InlinePolicy:
        Version: 2012-10-17
        Statement:
          - Sid: DenyEverything
            Effect: Deny
            Action: "*:*"
            Resource: "*"

  SimpleAssignmentGroup:
    Type: SSOUtil::SSO::AssignmentGroup
    Properties:
      Principal:
        PrincipalType: USER
        PrincipalId: c843295c-d41f-4f23-9832-1521dbaf36f7

      PermissionSet:
      - !GetAtt SomePSResource.PermissionSetArn

      Target:
      - Type: AWS_ACCOUNT
        TargetIds:
        - "123456789012"
        - "112233445566"

  ComplexAssignmentGroup:
    Type: SSOUtil::SSO::AssignmentGroup
    Properties:
      Name: Complex
      Principal:
      - Type: GROUP
        Id:
        - 6c1645fc-37b5-40ba-8c3d-5216b9055505
        - 67d02fc7-ef1e-463f-b572-ba9b2fe710ba

      - Type: USER
        Id: c843295c-d41f-4f23-9832-1521dbaf36f7

      PermissionSet:
      - arn:aws:sso:::permissionSet/ssoins-69e2ecd0b249f0cd/ps-45b2cb9e8a6aee12
      - ps-b5b9375180ceaaac
      - !GetAtt SomePSResource.PermissionSetArn

      Target:
      - Type: AWS_ACCOUNT
        Id: {"Ref": "AccountParameter"}
      - Type: AWS_ACCOUNT
        Id:
        - "123456789012"
        - "112233445566"
