# Randomly-generated but correctly formatted identifiers

# Instance: arn:aws:sso:::instance/ssoins-69e2ecd0b249f0cd

Groups:
- 6c1645fc-37b5-40ba-8c3d-5216b9055505
- 67d02fc7-ef1e-463f-b572-ba9b2fe710ba

Users:
- c843295c-d41f-4f23-9832-1521dbaf36f7
- !Ref UserParameter

PermissionSets:
- arn:aws:sso:::permissionSet/ssoins-69e2ecd0b249f0cd/ps-45b2cb9e8a6aee12
- ssoins-69e2ecd0b249f0cd/ps-04a493b762a3fef9
- ps-b5b9375180ceaaac
- !Ref SomePSResource
- Name: PermissionSetName
  ManagedPolicies: []

Ous:
# Using an OU will currently cause API calls to your account, so fake OU ID is commented out.
# - ou-7w1i-suzvrczk
RecursiveOus: []

Accounts:
- "123456789012"
- "112233445566"
- !Ref AccountParameter
